### ISSUE TITLE
move 40% faster with this one weird trick

### ISSUE THREAD

**Issue by no-lex** [OlRabiesAbe/baatar-bullet#1]
it's called holding multiple movement keys

or straferunning

You'll probably need to do some kind of normalization between the x,y components to make sure max speed is isotropic. Right now, it looks like (and acts like) the two axes are independent from each other.

**Comment by OlRabiesAbe** [comment]
fixed on baatar, mob will require reworking for implementation

**Comment by OlRabiesAbe** [comment]
fixed on mob
